/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/servicesTnt/serviceTnt.module';
import * as i2 from '../../node_modules/angular2-busy/build/busy.component.ngfactory';
import * as i3 from '../../node_modules/angular2-busy/build/busy-backdrop.component.ngfactory';
import * as i4 from '../../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as i5 from '../../node_modules/ng2-bootstrap/popover/popover-container.component.ngfactory';
import * as i6 from '../../node_modules/ng2-bootstrap/tooltip/tooltip-container.component.ngfactory';
import * as i7 from '../../node_modules/ng2-toastr/src/toast-container.component.ngfactory';
import * as i8 from './serviceTnt-list.component.ngfactory';
import * as i9 from './depot-detail.component.ngfactory';
import * as i10 from '@angular/common';
import * as i11 from 'angular2-busy/build/busy.module';
import * as i12 from '@angular/platform-browser';
import * as i13 from '@angular/animations/browser';
import * as i14 from '@angular/platform-browser/animations';
import * as i15 from '@angular/animations';
import * as i16 from 'angular2-busy/build/busy.service';
import * as i17 from 'angular2-busy/build/busy-config';
import * as i18 from '@angular/forms';
import * as i19 from 'ng2-bootstrap/positioning/positioning.service';
import * as i20 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as i21 from 'ng2-bootstrap/popover/popover.config';
import * as i22 from 'ng2-bootstrap/tooltip/tooltip.config';
import * as i23 from 'ng2-toastr/src/toast-options';
import * as i24 from '../../../app/shared/toastr-custom-option';
import * as i25 from 'ng2-toastr/src/toast-manager';
import * as i26 from '../../../app/shared/toastr.service';
import * as i27 from '../../../app/servicesTnt/serviceTnt.service';
import * as i28 from '@angular/http';
import * as i29 from '../../../app/servicesTnt/serviceTnt-guard.service';
import * as i30 from '@angular/router';
import * as i31 from 'ng2-bootstrap/modal/modal.module';
import * as i32 from 'ng2-bootstrap/popover/popover.module';
import * as i33 from 'ng2-bootstrap/tooltip/tooltip.module';
import * as i34 from 'ng2-toastr/src/toast.module';
import * as i35 from 'primeng/components/common/shared';
import * as i36 from 'primeng/components/dropdown/dropdown';
import * as i37 from 'primeng/components/paginator/paginator';
import * as i38 from 'primeng/components/inputtext/inputtext';
import * as i39 from 'primeng/components/datatable/datatable';
import * as i40 from 'primeng/components/multiselect/multiselect';
import * as i41 from 'primeng/components/togglebutton/togglebutton';
import * as i42 from '../../../app/shared/shared.module';
import * as i43 from '../../../app/servicesTnt/serviceTnt-list.component';
import * as i44 from '../../../app/servicesTnt/depot-detail.component';
export const ServiceTntModuleNgFactory:i0.NgModuleFactory<i1.ServiceTntModule> = i0.ɵcmf(i1.ServiceTntModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.BusyComponentNgFactory,i3.BusyBackdropComponentNgFactory,i4.ModalBackdropComponentNgFactory,
              i5.PopoverContainerComponentNgFactory,i6.TooltipContainerComponentNgFactory,
              i7.ToastContainerNgFactory,i8.ServiceTntListComponentNgFactory,i9.ServiceTntDetailComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i10.NgLocalization,i10.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.Compiler,i11.createJitCompiler,([] as any[])),
          i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i12.DomSanitizer,i12.ɵe,[i10.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i12.DomSanitizer]),i0.ɵmpd(4608,i12.HAMMER_GESTURE_CONFIG,
              i12.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i12.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i12.ɵDomEventsPlugin(p0_0),new i12.ɵKeyEventsPlugin(p1_0),
                    new i12.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i10.DOCUMENT,i10.DOCUMENT,i10.DOCUMENT,i12.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i12.EventManager,i12.EventManager,[i12.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i12.ɵDomSharedStylesHost,i12.ɵDomSharedStylesHost,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i12.ɵDomRendererFactory2,i12.ɵDomRendererFactory2,
              [i12.EventManager,i12.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i13.AnimationDriver,
              i14.ɵc,([] as any[])),i0.ɵmpd(5120,i13.ɵAnimationStyleNormalizer,i14.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i13.ɵAnimationEngine,i14.ɵb,[i13.AnimationDriver,
              i13.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i14.ɵe,
              [i12.ɵDomRendererFactory2,i13.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i12.ɵSharedStylesHost,(null as any),[i12.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i12.Meta,i12.Meta,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i12.Title,i12.Title,[i10.DOCUMENT]),i0.ɵmpd(4608,
              i15.AnimationBuilder,i14.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i16.BusyService,i16.BusyService,[[2,i17.BusyConfig]]),i0.ɵmpd(4608,
              i18.ɵi,i18.ɵi,([] as any[])),i0.ɵmpd(4608,i19.PositioningService,i19.PositioningService,
              ([] as any[])),i0.ɵmpd(4608,i20.ComponentLoaderFactory,i20.ComponentLoaderFactory,
              [i0.ComponentFactoryResolver,i0.NgZone,i0.Injector,i19.PositioningService]),
          i0.ɵmpd(4608,i21.PopoverConfig,i21.PopoverConfig,([] as any[])),i0.ɵmpd(4608,
              i22.TooltipConfig,i22.TooltipConfig,([] as any[])),i0.ɵmpd(4608,i23.ToastOptions,
              i24.CustomOption,([] as any[])),i0.ɵmpd(4608,i25.ToastsManager,i25.ToastsManager,
              [i0.ComponentFactoryResolver,i0.NgZone,i0.ApplicationRef,i23.ToastOptions]),
          i0.ɵmpd(4608,i26.ToastrService,i26.ToastrService,[i25.ToastsManager]),i0.ɵmpd(4608,
              i27.ServicesTntService,i27.ServicesTntService,[i28.Http]),i0.ɵmpd(4608,
              i29.ServiceTntDetailGuard,i29.ServiceTntDetailGuard,[i30.Router]),i0.ɵmpd(512,
              i10.CommonModule,i10.CommonModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i12.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any) => {
            return [i12.ɵc(p0_0,p0_1)];
          },[[2,i12.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i12.BrowserModule,i12.BrowserModule,[[3,i12.BrowserModule]]),
          i0.ɵmpd(512,i14.BrowserAnimationsModule,i14.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i11.BusyModule,i11.BusyModule,([] as any[])),i0.ɵmpd(512,i31.ModalModule,
              i31.ModalModule,([] as any[])),i0.ɵmpd(512,i32.PopoverModule,i32.PopoverModule,
              ([] as any[])),i0.ɵmpd(512,i33.TooltipModule,i33.TooltipModule,([] as any[])),
          i0.ɵmpd(512,i34.ToastModule,i34.ToastModule,([] as any[])),i0.ɵmpd(512,i35.SharedModule,
              i35.SharedModule,([] as any[])),i0.ɵmpd(512,i36.DropdownModule,i36.DropdownModule,
              ([] as any[])),i0.ɵmpd(512,i18.ɵba,i18.ɵba,([] as any[])),i0.ɵmpd(512,
              i18.FormsModule,i18.FormsModule,([] as any[])),i0.ɵmpd(512,i37.PaginatorModule,
              i37.PaginatorModule,([] as any[])),i0.ɵmpd(512,i38.InputTextModule,i38.InputTextModule,
              ([] as any[])),i0.ɵmpd(512,i39.DataTableModule,i39.DataTableModule,([] as any[])),
          i0.ɵmpd(512,i40.MultiSelectModule,i40.MultiSelectModule,([] as any[])),i0.ɵmpd(512,
              i41.ToggleButtonModule,i41.ToggleButtonModule,([] as any[])),i0.ɵmpd(512,
              i42.SmSharedModule,i42.SmSharedModule,([] as any[])),i0.ɵmpd(512,i30.RouterModule,
              i30.RouterModule,[[2,i30.ɵa],[2,i30.Router]]),i0.ɵmpd(512,i1.ServiceTntModule,
              i1.ServiceTntModule,([] as any[])),i0.ɵmpd(256,i17.BusyConfig,{delay:0,
              minDuration:0,backdrop:true,message:'Proszę czekać...',template:'\n        <div class="ng-busy-default-wrapper">\n            <div class="ng-busy-default-sign">\n                <div class="ng-busy-default-spinner">\n                    <div class="bar1"></div>\n                    <div class="bar2"></div>\n                    <div class="bar3"></div>\n                    <div class="bar4"></div>\n                    <div class="bar5"></div>\n                    <div class="bar6"></div>\n                    <div class="bar7"></div>\n                    <div class="bar8"></div>\n                    <div class="bar9"></div>\n                    <div class="bar10"></div>\n                    <div class="bar11"></div>\n                    <div class="bar12"></div>\n                </div>\n                <div class="ng-busy-default-text">{{message}}</div>\n            </div>\n        </div>\n    ',
              wrapperClass:'ng-busy'},([] as any[])),i0.ɵmpd(1024,i30.ROUTES,() => {
            return [[{path:'serviceTnt',component:i43.ServiceTntListComponent},{path:'serviceTnt/:id',
                canActivate:[i29.ServiceTntDetailGuard],component:i44.ServiceTntDetailComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVrdHkvU2VydmljZU1hcC9TZXJ2aWNlTWFwL3NyYy9TZXJ2aWNlTWFwL3d3d3Jvb3QvYXBwL3NlcnZpY2VzVG50L3NlcnZpY2VUbnQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2pla3R5L1NlcnZpY2VNYXAvU2VydmljZU1hcC9zcmMvU2VydmljZU1hcC93d3dyb290L2FwcC9zZXJ2aWNlc1RudC9zZXJ2aWNlVG50Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
