/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.panel-primary[_ngcontent-%COMP%]    > .panel-heading[_ngcontent-%COMP%] {\r\n    border-color: white;\r\n}\r\n\r\n.container-in-form-psz[_ngcontent-%COMP%] {\r\n    \r\n	background:#1367AD none repeat scroll 0 0;\r\n	color: #FFF;\r\n	 border: 1px solid #666666;\r\n    padding: 10px;\r\n    top: 20px;\r\n    margin-left: 0 !important;\r\n    margin-right: 0 !important;\r\n    margin-bottom: 15px;\r\n    position: static;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVrdHkvU2VydmljZU1hcC9TZXJ2aWNlTWFwL3NyYy9TZXJ2aWNlTWFwL3d3d3Jvb3QvYXBwL3NlcnZpY2VzVG50L3NlcnZpY2VUbnQtbGlzdC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2pla3R5L1NlcnZpY2VNYXAvU2VydmljZU1hcC9zcmMvU2VydmljZU1hcC93d3dyb290L2FwcC9zZXJ2aWNlc1RudC9zZXJ2aWNlVG50LWxpc3QuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
