/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../app/app.module';
import * as i2 from '../../app/app.component';
import * as i3 from '../node_modules/angular2-busy/build/busy.component.ngfactory';
import * as i4 from '../node_modules/angular2-busy/build/busy-backdrop.component.ngfactory';
import * as i5 from '../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as i6 from '../node_modules/ng2-bootstrap/popover/popover-container.component.ngfactory';
import * as i7 from '../node_modules/ng2-bootstrap/tooltip/tooltip-container.component.ngfactory';
import * as i8 from '../node_modules/ng2-toastr/src/toast-container.component.ngfactory';
import * as i9 from './users/user-list.component.ngfactory';
import * as i10 from './users/user.component.ngfactory';
import * as i11 from './servicesTnt/serviceTnt-list.component.ngfactory';
import * as i12 from './servicesTnt/depot-detail.component.ngfactory';
import * as i13 from './app.component.ngfactory';
import * as i14 from '@angular/http';
import * as i15 from '@angular/forms';
import * as i16 from '@angular/common';
import * as i17 from '@angular/platform-browser';
import * as i18 from '@angular/animations/browser';
import * as i19 from '@angular/platform-browser/animations';
import * as i20 from '@angular/animations';
import * as i21 from 'angular2-busy/build/busy.service';
import * as i22 from 'angular2-busy/build/busy-config';
import * as i23 from 'ng2-bootstrap/positioning/positioning.service';
import * as i24 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as i25 from 'ng2-bootstrap/popover/popover.config';
import * as i26 from 'ng2-bootstrap/tooltip/tooltip.config';
import * as i27 from 'ng2-toastr/src/toast-options';
import * as i28 from '../../app/shared/toastr-custom-option';
import * as i29 from 'ng2-toastr/src/toast-manager';
import * as i30 from '../../app/shared/toastr.service';
import * as i31 from '../../app/users/user.service';
import * as i32 from '../../app/users/user-guard.service';
import * as i33 from '@angular/router';
import * as i34 from '../../app/servicesTnt/serviceTnt.service';
import * as i35 from '../../app/servicesTnt/serviceTnt-guard.service';
import * as i36 from 'angular2-busy/build/busy.module';
import * as i37 from '../../app/users/user-list.component';
import * as i38 from '../../app/users/user.component';
import * as i39 from '../../app/servicesTnt/serviceTnt-list.component';
import * as i40 from '../../app/servicesTnt/depot-detail.component';
import * as i41 from 'ng2-bootstrap/modal/modal.module';
import * as i42 from 'ng2-bootstrap/popover/popover.module';
import * as i43 from 'ng2-bootstrap/tooltip/tooltip.module';
import * as i44 from 'ng2-toastr/src/toast.module';
import * as i45 from 'primeng/components/common/shared';
import * as i46 from 'primeng/components/dropdown/dropdown';
import * as i47 from 'primeng/components/paginator/paginator';
import * as i48 from 'primeng/components/inputtext/inputtext';
import * as i49 from 'primeng/components/datatable/datatable';
import * as i50 from 'primeng/components/multiselect/multiselect';
import * as i51 from 'primeng/components/togglebutton/togglebutton';
import * as i52 from '../../app/shared/shared.module';
import * as i53 from '../../app/users/user-module';
import * as i54 from '../../app/servicesTnt/serviceTnt.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.BusyComponentNgFactory,i4.BusyBackdropComponentNgFactory,i5.ModalBackdropComponentNgFactory,
              i6.PopoverContainerComponentNgFactory,i7.TooltipContainerComponentNgFactory,
              i8.ToastContainerNgFactory,i9.UserListComponentNgFactory,i10.UserComponentNgFactory,
              i11.ServiceTntListComponentNgFactory,i12.ServiceTntDetailComponentNgFactory,
              i13.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i14.BrowserXhr,i14.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i14.ResponseOptions,
              i14.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i14.XSRFStrategy,
              i14.ɵb,([] as any[])),i0.ɵmpd(4608,i14.XHRBackend,i14.XHRBackend,[i14.BrowserXhr,
              i14.ResponseOptions,i14.XSRFStrategy]),i0.ɵmpd(4608,i14.RequestOptions,
              i14.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i14.Http,i14.ɵc,[i14.XHRBackend,
              i14.RequestOptions]),i0.ɵmpd(4608,i15.FormBuilder,i15.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i15.ɵi,i15.ɵi,([] as any[])),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,
              [[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i16.NgLocalization,i16.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
              i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i17.DomSanitizer,i17.ɵe,[i16.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i17.DomSanitizer]),i0.ɵmpd(4608,
              i17.HAMMER_GESTURE_CONFIG,i17.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i17.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i17.ɵDomEventsPlugin(p0_0),new i17.ɵKeyEventsPlugin(p1_0),
                    new i17.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i16.DOCUMENT,i16.DOCUMENT,i16.DOCUMENT,i17.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i17.EventManager,i17.EventManager,[i17.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i17.ɵDomSharedStylesHost,i17.ɵDomSharedStylesHost,
              [i16.DOCUMENT]),i0.ɵmpd(4608,i17.ɵDomRendererFactory2,i17.ɵDomRendererFactory2,
              [i17.EventManager,i17.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i18.AnimationDriver,
              i19.ɵc,([] as any[])),i0.ɵmpd(5120,i18.ɵAnimationStyleNormalizer,i19.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i18.ɵAnimationEngine,i19.ɵb,[i18.AnimationDriver,
              i18.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i19.ɵe,
              [i17.ɵDomRendererFactory2,i18.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i17.ɵSharedStylesHost,(null as any),[i17.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i17.Meta,i17.Meta,
              [i16.DOCUMENT]),i0.ɵmpd(4608,i17.Title,i17.Title,[i16.DOCUMENT]),i0.ɵmpd(4608,
              i20.AnimationBuilder,i19.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i21.BusyService,i21.BusyService,[[2,i22.BusyConfig]]),i0.ɵmpd(4608,
              i23.PositioningService,i23.PositioningService,([] as any[])),i0.ɵmpd(4608,
              i24.ComponentLoaderFactory,i24.ComponentLoaderFactory,[i0.ComponentFactoryResolver,
                  i0.NgZone,i0.Injector,i23.PositioningService]),i0.ɵmpd(4608,i25.PopoverConfig,
              i25.PopoverConfig,([] as any[])),i0.ɵmpd(4608,i26.TooltipConfig,i26.TooltipConfig,
              ([] as any[])),i0.ɵmpd(4608,i27.ToastOptions,i28.CustomOption,([] as any[])),
          i0.ɵmpd(4608,i29.ToastsManager,i29.ToastsManager,[i0.ComponentFactoryResolver,
              i0.NgZone,i0.ApplicationRef,i27.ToastOptions]),i0.ɵmpd(4608,i30.ToastrService,
              i30.ToastrService,[i29.ToastsManager]),i0.ɵmpd(4608,i31.UserService,
              i31.UserService,[i14.Http]),i0.ɵmpd(4608,i32.UserDetailGuard,i32.UserDetailGuard,
              [i33.Router]),i0.ɵmpd(4608,i32.UserEditGuard,i32.UserEditGuard,([] as any[])),
          i0.ɵmpd(4608,i34.ServicesTntService,i34.ServicesTntService,[i14.Http]),i0.ɵmpd(4608,
              i35.ServiceTntDetailGuard,i35.ServiceTntDetailGuard,[i33.Router]),i0.ɵmpd(5120,
              i33.ActivatedRoute,i33.ɵf,[i33.Router]),i0.ɵmpd(4608,i33.NoPreloading,
              i33.NoPreloading,([] as any[])),i0.ɵmpd(6144,i33.PreloadingStrategy,
              (null as any),[i33.NoPreloading]),i0.ɵmpd(135680,i33.RouterPreloader,
              i33.RouterPreloader,[i33.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i33.PreloadingStrategy]),i0.ɵmpd(4608,i33.PreloadAllModules,
              i33.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i33.ROUTER_INITIALIZER,
              i33.ɵi,[i33.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i33.ROUTER_INITIALIZER]),i0.ɵmpd(512,i14.HttpModule,i14.HttpModule,([] as any[])),
          i0.ɵmpd(512,i15.ɵba,i15.ɵba,([] as any[])),i0.ɵmpd(512,i15.ReactiveFormsModule,
              i15.ReactiveFormsModule,([] as any[])),i0.ɵmpd(1024,i33.ɵa,i33.ɵd,[[3,
              i33.Router]]),i0.ɵmpd(1024,i0.ErrorHandler,i17.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i33.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i33.ɵg,i33.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i17.ɵc(p0_0,p0_1),i33.ɵh(p1_0)];
              },[[2,i17.NgProbeToken],[2,i0.NgProbeToken],i33.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i33.UrlSerializer,i33.DefaultUrlSerializer,([] as any[])),
          i0.ɵmpd(512,i33.ChildrenOutletContexts,i33.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i33.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i16.LocationStrategy,
              i33.ɵc,[i16.PlatformLocation,[2,i16.APP_BASE_HREF],i33.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i16.Location,i16.Location,[i16.LocationStrategy]),i0.ɵmpd(1024,
              i0.Compiler,i36.createJitCompiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i33.ROUTES,() => {
            return [[{path:'userlist',component:i37.UserListComponent},{path:'adduser',
                canDeactivate:[i32.UserEditGuard],canActivate:[i32.UserDetailGuard],
                component:i38.UserComponent}],[{path:'serviceTnt',component:i39.ServiceTntListComponent},
                {path:'serviceTnt/:id',canActivate:[i35.ServiceTntDetailGuard],component:i40.ServiceTntDetailComponent}],
                [{path:'serviceTnt',component:i39.ServiceTntListComponent},{path:'',
                    redirectTo:'serviceTnt',pathMatch:'full'},{path:'**',redirectTo:'serviceTnt',
                    pathMatch:'full'}]];
          },([] as any[])),i0.ɵmpd(1024,i33.Router,i33.ɵe,[i0.ApplicationRef,i33.UrlSerializer,
              i33.ChildrenOutletContexts,i16.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i33.ROUTES,i33.ROUTER_CONFIGURATION,[2,i33.UrlHandlingStrategy],
              [2,i33.RouteReuseStrategy]]),i0.ɵmpd(512,i33.RouterModule,i33.RouterModule,
              [[2,i33.ɵa],[2,i33.Router]]),i0.ɵmpd(512,i16.CommonModule,i16.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,
              [i0.ApplicationRef]),i0.ɵmpd(512,i17.BrowserModule,i17.BrowserModule,
              [[3,i17.BrowserModule]]),i0.ɵmpd(512,i19.BrowserAnimationsModule,i19.BrowserAnimationsModule,
              ([] as any[])),i0.ɵmpd(512,i36.BusyModule,i36.BusyModule,([] as any[])),
          i0.ɵmpd(512,i41.ModalModule,i41.ModalModule,([] as any[])),i0.ɵmpd(512,i42.PopoverModule,
              i42.PopoverModule,([] as any[])),i0.ɵmpd(512,i43.TooltipModule,i43.TooltipModule,
              ([] as any[])),i0.ɵmpd(512,i44.ToastModule,i44.ToastModule,([] as any[])),
          i0.ɵmpd(512,i45.SharedModule,i45.SharedModule,([] as any[])),i0.ɵmpd(512,
              i46.DropdownModule,i46.DropdownModule,([] as any[])),i0.ɵmpd(512,i15.FormsModule,
              i15.FormsModule,([] as any[])),i0.ɵmpd(512,i47.PaginatorModule,i47.PaginatorModule,
              ([] as any[])),i0.ɵmpd(512,i48.InputTextModule,i48.InputTextModule,([] as any[])),
          i0.ɵmpd(512,i49.DataTableModule,i49.DataTableModule,([] as any[])),i0.ɵmpd(512,
              i50.MultiSelectModule,i50.MultiSelectModule,([] as any[])),i0.ɵmpd(512,
              i51.ToggleButtonModule,i51.ToggleButtonModule,([] as any[])),i0.ɵmpd(512,
              i52.SmSharedModule,i52.SmSharedModule,([] as any[])),i0.ɵmpd(512,i53.ProductModule,
              i53.ProductModule,([] as any[])),i0.ɵmpd(512,i54.ServiceTntModule,i54.ServiceTntModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i22.BusyConfig,{delay:0,minDuration:0,backdrop:true,message:'Proszę czekać...',
              template:'\n        <div class="ng-busy-default-wrapper">\n            <div class="ng-busy-default-sign">\n                <div class="ng-busy-default-spinner">\n                    <div class="bar1"></div>\n                    <div class="bar2"></div>\n                    <div class="bar3"></div>\n                    <div class="bar4"></div>\n                    <div class="bar5"></div>\n                    <div class="bar6"></div>\n                    <div class="bar7"></div>\n                    <div class="bar8"></div>\n                    <div class="bar9"></div>\n                    <div class="bar10"></div>\n                    <div class="bar11"></div>\n                    <div class="bar12"></div>\n                </div>\n                <div class="ng-busy-default-text">{{message}}</div>\n            </div>\n        </div>\n    ',
              wrapperClass:'ng-busy'},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVrdHkvU2VydmljZU1hcC9TZXJ2aWNlTWFwL3NyYy9TZXJ2aWNlTWFwL3d3d3Jvb3QvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVrdHkvU2VydmljZU1hcC9TZXJ2aWNlTWFwL3NyYy9TZXJ2aWNlTWFwL3d3d3Jvb3QvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
